import React from "react";

import "./AboutSection.css"

import img1 from "../assets/image_5.jpg"
import img2 from "../assets/image_8.jpg"
import img3 from "../assets/image_3.jpg"
import img4 from "../assets/image_10.jpg"
import img5 from "../assets/image_2.jpg"



const cards = [
  {
    title: "National Reach, Local Luxury",
    description:
      "Access the most prestigious properties in every corner of the country. From secluded coastal retreats to vibrant metropolitan suites, our platform maps the pinnacle of local hospitality to a single, seamless interface.",
    button: "Explore Destinations",
    image:img1,
    dark: false,
  },
  {
    title: "24/7 Concierge Support",
    description:
      "Our commitment to your experience never sleeps. Benefit from around-the-clock professional support designed to handle every request with urgency and discretion.",
    button: "Contact Concierge",
    image:img2,
    dark: true,
  },
  {
    title: "Verified Reviews & Ratings",
    description:
      "Trust is our core currency. Every rating and review on LuxeStay Collective is generated by verified guests who have completed their stays.",
    button: "View Testimonials",
    image:img3,
    dark: false,
  },
];

const AboutSection = () => {
  return (
    <section className="about-section">
      {/* LEFT SIDE */}
      <div className="left-content">
        <button className="top-btn">About Deluxe Bookings</button>

        <h1>
          Designed for Discerning <br />
          Travellers
        </h1>

        <p>
          Deluxe Bookings bridges the gap between local luxury and global
          standards. We provide a sophisticated ecosystem where booking
          excellence is the baseline, and your peace of mind is our priority.
          Experience hospitality reimagined through intelligent design and
          verified trust.
        </p>

        <div className="gallery">
          <img
            src={img4}
            alt=""
          />

          <img
            src={img5}
            alt=""
          />
        </div>
      </div>

      {/* RIGHT SIDE */}
      <div className="right-content">
        {cards.map((card, index) => (
          <div
            className={`info-card ${card.dark ? "dark-card" : ""}`}
            key={index}
          >
            <div className="card-text">
              <h2>{card.title}</h2>

              <p>{card.description}</p>

              <button className="card-btn">
                {card.button}

                <span>↗</span>
              </button>
            </div>

            <div className="card-image">
              <img src={card.image} alt="" />
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default AboutSection;